### ISSUE TITLE
Add CI/CD to template

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/backend-nestjs-template#11]
### Story
Add CI/CD for PR's. Every PR should have a CI/CD pipeline to achieve quicker testing and use for every PR.
Include CI/CD for mock service, using the image m3ntoshipci/prism for mocking.

### Prerequisites
None

### Tasks
- [ ] Create Github Action workflow, with the following jobs:
  - [ ] Build and push for docker image
  - [ ] Deployment (needs Kubernetes)
  - [ ] Undeploy after merge/close
  - [ ] Delete Docker images made for this PR after merge/close
- [ ] Kubernetes components:
  - [ ] Deployments
  - [ ] Services
  - [ ] Ingress

### Acceptance criteria
- Complete CI/CD for both base service and mock service for every PR.
